    @startuml
(*)  --> "window: request email and password"
if "" then
    --> [cancel] "**ACTIVITYLOGIN**"
    --> [redirect] (*)
else
    --> [continue] "server: validate Email"
    --> "server: validate password"
    if "" then
        --> [valid] "server: quest or reqular user"
        if "" then
            --> [quest user] "selection-popup: request is //invited// quest or internal (student or employee)"
            if "" then
                --> [invited guest] "input-popup: emailaddress of validator (employee)"
                --> "server: db-create regular quest user"
                --> "server: send validation request to employee"
                if "" then
                    --> [validated] "server: db-update to premium quest user"
                    --> [invited guest] "**ACTIVITYEMAILVERIFICATION**"
                else
                    --> [not valid] "server: db-create reqular quest user"
                    --> [guest] "**ACTIVITYEMAILVERIFICATION**"
                Endif
            else
                --> [regular guest] "**ACTIVITYEMAILVERIFICATION**"
                --> "notification: email sent"
                --> [success] (*)
            Endif
        else
            --> [internal user] "server: validate employee or student email"
            if "" then
                --> [student] "server: db-create student user"
                --> [student] "**ACTIVITYEMAILVERIFICATION**"
            else
                --> [employee] "server: db-create employee user"
                --> [employee] "**ACTIVITYEMAILVERIFICATION**"
            Endif
        Endif
    else
        --> [invalid] "retry-popup: retry email and password input"
        if "" then
            --> [abort] "**ACTIVITYLOGIN**"
        else
            --> [retry] "window: request email and password"
        Endif
    else
        --> [already registered] "yes-no-popup: reset password request"
        if "" then
            --> [change pw] "**ACTIVITYCHANGEPASSWORD**"
            --> "notification: email sent"
        else
            --> [abort] "window: request email and password"
        Endif
    Endif
Endif
@enduml