    @startuml
(*) --> "window: change app setting"
if "" then
    --> [cancel] (*)
else
    --> [continue] "server: db-get user or worker"
    if "" then
        --> [worker] "worker"
        if "" then
            --> [notifications] "**ACTIVITYNOTIFACTIONS**"
        else
            if "" then
                --> [tracking] "**ACTIVITYTRACKING**"
            else
                if "" then
                    --> [privacy] "**ACTIVITYPRIVACY**"
                else
                    --> [performance] "**ACTIVITYPERFORMANCE**"
                    --> "save-cancel-action"
                    if "" then
                        --> [save] "server: db-update saved user setting"
                        --> [updated] (*)
                    else
                        --> [cancel] "window: change app setting"
                    Endif
                Endif
            Endif
        Endif
    else
        --> [student] "student"
        if "" then
            --> [notifications] "**ACTIVITYNOTIFACTIONS**"
        else
            if "" then
                --> [tracking] "**ACTIVITYTRACKING**"
            else
                if "" then
                    --> [privacy] "**ACTIVITYPRIVACY**"
                else
                    --> [performance] "**ACTIVITYPERFORMANCE**"
                    --> "save-cancel-action"
                Endif
            Endif
        Endif
    Endif
Endif
@enduml
