@startuml
(*) --> "window: change personal setting"
if "" then
    --> [cancel] (*)
else
    --> [continue] "server: db-get user or worker"
    if "" then
        --> [worker] "worker"
        if "" then
            --> [email] "**ACTIVITYCHANGEEMAIL**"
        else
            if "" then
                --> [password] "**ACTIVITYCHANGEPASSWORD**"
            else
                if "" then
                    --> [mobilephone] "**ACTIVITYCHANGEMOBILE**"
                else
                    if "" then
                        --> [faculty] "select-window:\n faculty-chooser\n request is faculty visible for which group/department/faculty"
                        --> "save-cancel-action"
                        if "" then
                            --> [save] "server: db-update saved user setting"
                            --> [updated] (*)
                        else
                            --> [cancel] "window: change personal setting"
                        Endif
                    else
                        if "" then
                            --> [officephone] "input-window:\n telephone number\n is phone visible for which group/department/faculty"
                            --> "save-cancel-action"
                        else
                            if "" then
                                --> [office] "input-window:\n office number\n is office visible for which group/department/faculty"
                                --> "save-cancel-action"
                            else
                                --> [specialrole] "select-multiple-window:\n select special roles\n is/are role(s) visible for which group/department/faculty"
                                --> "save-cancel-action"
                            Endif
                        Endif
                    Endif
                Endif
            Endif
        Endif
    else
        --> [student] "student"
        if "" then
            --> [email] "**ACTIVITYCHANGEEMAIL**"
        else
            if "" then
                --> [password] "**ACTIVITYCHANGEPASSWORD**"
            else
                if "" then
                    --> [mobilephone] "**ACTIVITYCHANGEMOBILE**"
                else
                    --> [faculty] "select-window:\n faculty-chooser\n"
                    --> "save-cancel-action"
                Endif
            Endif
        Endif
    Endif
Endif
@enduml
