    @startuml
(*) --> "window: change personal setting"
if "" then
    --> [cancel] (*)
else
    if "" then
        --> [profilepicture] "upload-window: save new profilepicture"
        --> "save-cancel-action"
        if "" then
            --> [save] "server: db-update saved user setting"
            --> [updated] "window: change personal setting"
        else
            --> [cancel] "window: change personal setting"
        Endif
    else
        if "" then
            --> [email] "**ACTIVITYCHANGEEMAIL**"
        else
            if "" then
                --> [password] "**ACTIVITYCHANGEPASSWORD**"
            else
                if "" then
                    --> [mobilephone] "**ACTIVITYCHANGEMOBILE**"
                else
                    --> [continue] "server: db-get user or worker"
                    if "" then
                        --> [student faculty] "select-window:\n faculty-chooser\n"
                        --> "save-cancel-action"
                    else
                        --> [worker workspace] "worker"
                        if "" then
                            --> [workspace] "select-window:\n workspace-chooser\n request is faculty visible for which group/department/faculty"
                        else
                            if "" then
                                --> [officephone] "input-window:\n telephone number\n is phone visible for which group/department/faculty"
                                --> "save-cancel-action"
                            else
                                if "" then
                                    --> [office] "input-window:\n office number\n is office visible for which group/department/faculty"
                                    --> "save-cancel-action"
                                else
                                    --> [specialrole] "select-multiple-window:\n select special roles\n is/are role(s) visible for which group/department/faculty"
                                    --> "save-cancel-action"
                                Endif
                            Endif
                        Endif
                    Endif
                Endif
            Endif
        Endif
    Endif
Endif
@enduml
