    @startuml
(*) --> "window: change app setting"
if "" then
    --> [cancel] (*)
else
    --> [continue] "server: db-get user or worker"
    if "" then
        --> [notifications] "get redirect to settings or manual"
        if "" then
            --> [manual] "server: db-read device notification manual"
            --> "close-popup: show notification manual"
            --> [close] "window: change app setting"
        else
            --> [settings] "redirect to device notification settings"
            --> [notification settings] "window: change app setting"
        Endif
    else
        --> [tracking] "**ACTIVITYTRACKING**"
        --> "save-cancel-action"
        if "" then
            --> [save] "server: db-update saved user setting"
            --> [updated] "window: change app setting"
        else
            --> [cancel] "window: change app setting"
        Endif
    Endif
Endif
@enduml
