@startuml
(*)  --> "window: request email"
if "" then
    --> [continue] "server: validate Email"
    if "" then
        --> [valid] "window: request password"
        --> "server: validate password"
        if "" then
            --> [valid] "server: db-create user"
            --> [pending] "ACTIVITYEMAILVERIFICATION"
            --> (*)
        else
            --> [invalid] "retry-popup: retry password input"
            if "" then
                --> [abort] "window: request email"
            else
                --> [retry] "window: request password"
            Endif
        Endif
    else
        --> [already registered] "yes-no-popup: reset password request"
        if "" then
            --> [Yes] "ACTIVITYCHANGEPASSWORD"
            --> "window: request password"
        else
            --> [No] "retry-popup: retry registration"
            if "" then
                --> [abort] "ACTIVITYLOGIN"
            else
                --> [retry] "window: request email"
            Endif
        Endif
    Endif
else
    --> [cancel] "ACTIVITYLOGIN"
Endif
@enduml