@startuml
(*)  --> "window: request email"
--> "server: db-read validate mail"
if "" then
    --> [valid] "window: request password"
    --> "server: db-read validate password with slow hash"
    if "" then
        --> [valid] "server: db-update user logged in"
        --> (*)
    else
        --> [wait x seconds] "server: ACTIVITYBLOCKTIMER"
        if "" then
            --> [5 tries in one hour] "server: ACTIVITYBLOCKTIMER"
            --> [after one hour] "window: request password"
        else
            --> [after x seconds] "window: request password"
        Endif
    Endif
else
    if "" then
        --> [email not verified] "ACTIVITYEMAILVERIFICATION"
        --> "window: request email"
    else
        --> [email not registered] "register-cancel-popup: email not registered"
        if "" then
            --> [register] "ACTIVITYREGISTER"
            --> "window: request email"
        else
            --> [cancel] "window: request email"
        Endif
    Endif
Endif
@enduml