@startuml
(*) --> "change single setting"
if "" then
    --> [email] "input-window:\n request email change and confirmation\n request is email visible for which group/department)"
    --> "ACTIVITYEMAILVERIFICATION"
    if "" then
        --> [save] "server: db-update user log out"
        --> "server: db-update user settings"
        --> (*)
    else
        --> [abort] "ACTIVITYSETTINGS"
    Endif
else
    if "" then
        --> [password] "ACTIVITYCHANGEPASSWORD"
        if "" then
            --> [valid and save password] "server: db-update user settings"
        else
            --> [abort] "ACTIVITYSETTINGS"
        Endif
    else
        if "" then
            --> [faculty] "select-window:\n faculty-chooser\n request is email visible for which group/(department)/faculty"
            if "" then
                --> [save faculty] "server: db-update user settings"
            else
                --> [abort] "ACTIVITYSETTINGS"
            Endif
        else
            if "" then
                --> [department] "select-window:\n department-chooser\n request is email visible for which group/department/faculty)"
                if "" then
                    --> [save faculty] "server: db-update user settings"
                else
                    --> [abort] "ACTIVITYSETTINGS"
                Endif
            else
                if "" then
                    --> [phone] "input-window:\n telephone number\n is phone visible for which group/department/faculty"
                    --> "server: send sms verification link"
                    if "" then
                        --> [saved and verified] "server: db-update user settings"
                    else
                        --> [abort] "ACTIVITYSETTINGS"
                    Endif
                else
                    --> [office] "input-windw:\n office room number\n is office visible for which group/department/faculty"



@enduml