@startuml
(*)  --> "email verification notification"
if "" then
    --> [not verified] "Want to resend verification"
    if "" then
        --> [Yes] "server: send email verification"
        if "" then
            --> [valid request] "server: send email verification link"
            --> "email verification notification"
        else
            --> [more than 5 requests in last hour] "server: ACTIVITYBLOCKTIMER"
            --> "email verification notification"
        Endif
    else
        --> [abort] "ACTIVITYREGISTER"
    Endif
else
    --> [verified] (*)
Endif
@enduml