@startuml
(*) --> "server: db-read user by id (cookie on phone)"
--> "server: validate user registration and cookie"
if "" then
    --> [valid] "server: db-read is admin user"
    if "" then
        --> [normal user] "**ACTIVITYMAIN**"
        --> (*)
    else
        --> [admin user] "//choose-popup: Login as admin or normal user//"
        if "" then
            --> [yes] "//**ACTIVITYADMIN**//"
            --> (*)
        else
            --> [no] "**ACTIVITYMAIN**"
        Endif
    Endif
else
    --> [invalid] "choose-popup: login or register"
    If "" then
        --> [login] "**ACTIVITYLOGIN**"
        --> (*)
    else
        --> [register] "**ACTIVITYREGISTER**"
        --> (*)
    Endif
Endif
@enduml