    @startuml
(*)  --> "request-window: change link per email or sms"
if "" then
    --> [cancel] (*)
else
    if "" then
        --> [email] "server: send email with tokenized password change link"
        --> "server: change link clicked"
    else
        --> [sms] "server: send sms with tokenized password change link"
    Endif
    --> "server: change link clicked"
    if "" then
        --> [no change] "server: use old password for authentication"
        --> [cancel] "request-window: change link per email or sms"
    else
        --> [change pw] "input-window: new password and confirmation"
        --> "server: db-update user, keep old pw, send notification email with tokenized link for pw reset to mobile and email"
        if "" then
            --> [reset old pw] "server: db-update restore old password, db-delete new pw"
            --> [reset old pw] (*)
        else
            --> [use new pw] "server: db-delete old pw after 7 days"
            --> [new pw] (*)
        Endif
    Endif
Endif
@enduml